### ISSUE TITLE
Update to Node.js v20

### ISSUE THREAD

**Issue by mcollina** [pnpm/action-setup#113]
When using this action I'm getting:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: pnpm/action-setup@v2.4.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by zkochan** [comment]
There's a PR about it https://github.com/pnpm/action-setup/pull/110
