### ISSUE TITLE
should upgrade node16 to node20

### ISSUE THREAD

**Issue by sukvvon** [pnpm/action-setup#114]
i saw #99 

<img width="914" alt="image" src="https://github.com/dnd-side-project/dnd-10th-5-frontend/assets/66409882/8f7b9f6b-e538-42d4-a352-b1481fb79a6c">

i think `pnpm/action-setup` should upgrade node16 to node20 because github will not support node16 soon

does upgrading node16 to node20 in `pnpm/action-setup` impossible??
are this team fixing this problem?? 🤔

**Comment by zkochan** [comment]
Don't open a duplicate issue.

There is a PR: https://github.com/pnpm/action-setup/pull/110
