### ISSUE TITLE
Add support for grabbing `version` from the `engines.pnpm` field

### ISSUE THREAD

**Issue by Stanzilla** [pnpm/action-setup#123]
Currently the action is able to grab the `version` from the `packageManager` field which causes a few side effects.

If a user wants the repo to use a specified version of pnpm but not down to the patch level version, it was recommended to set the `engines.pnpm` field instead since `packageManager` does not support ranges. 

It would be nice if the action supported reading this field as well.

Related: 
- https://github.com/pnpm/action-setup/pull/122
- https://github.com/pnpm/action-setup/issues/54

**Comment by karlhorky** [comment]
Is this a duplicate of https://github.com/pnpm/action-setup/issues/84 ?

**Comment by Stanzilla** [comment]
> Is this a duplicate of #84 ?

Oh yes, my bad, sorry!
