### ISSUE TITLE
Content-addressable is on wrong drive on windows platform

### ISSUE THREAD

**Issue by domiSchenk** [pnpm/action-setup#15]
I'am playing around with pnpm on github actions and caching for faster builds.

Unfortunately after installing pnpm (btw has the right path: `Content-addressable store is at: C:\Users\runneradmin\.pnpm-store\v3`) its using a diffrent one for installing:  `Content-addressable store is at: D:\.pnpm-store\v3`

- where could here be the problem? 
- are there some hard-coded links? 
- does it matter if its on D on my PC?

here is the last log:
https://github.com/domiSchenk/gh-action-pnpm-win-test/actions/runs/985157004

**Comment by KSXGitHub** [comment]
![screenshot of logs](https://user-images.githubusercontent.com/11488886/123911992-b0dcf000-d9a6-11eb-8ec6-391f548d3845.png)

pnpm/action-setup has two stages:
1. Installing `pnpm` itself to C drive (blue).
2. Installing dependencies in `package.json` to D drive (red).

`pnpm` itself is still in C drive and is hardlinked to a store in C drive. The `node_modules` files are in D drive and is hardlinked to a store in D drive.

**Comment by domiSchenk** [comment]
okey, but does github action have the D drive?

**Comment by KSXGitHub** [comment]
> okey, but does github action have the D drive?

Ask the people who made GitHub Actions, not me.

**Comment by domiSchenk** [comment]
Thanks for your help.
I did not think windows would checkout on different drive :-(
