### ISSUE TITLE
[feature request] Use version of pnpm specified in package.json

### ISSUE THREAD

**Issue by Jack-Works** [pnpm/action-setup#24]
There's two way to specify pnpm version in package.json:

```jsonc
{
  "packageManager": "pnpm@6.23.1",
  "engines": {
    "pnpm": ">=6"
  },
}
```

It should prefer [packageManager field](https://nodejs.org/api/corepack.html) because it is more precise (this field does not support semver).

**Comment by zkochan** [comment]
TBH, I would be happy to deprecate the `engines.pnpm` field but I think it is too strict to only allow exact versions in the `packageManager` field.

**Comment by Jack-Works** [comment]
I think `engines.pnpm` is okay since yarn also supports it IIRC (`engines.yarn`?)
