### ISSUE TITLE
Doesn't work with pnpm v7

### ISSUE THREAD

**Issue by zkochan** [pnpm/action-setup#28]
I just release pnpm v7.0.0-alpha.0 and for some reason it doesn't work with this action. Looks like it doesn't appear in the PATH. Might be related to this: https://github.com/pnpm/pnpm/pull/4280

**Comment by KSXGitHub** [comment]
This action only calls the self installer provided by pnpm: https://github.com/pnpm/action-setup/blob/7c4472dbcf6f5e617e536d979f28d932ef243ad9/src/install-pnpm/run.ts#L8-L29
