### ISSUE TITLE
pnpm action does not support Windows

### ISSUE THREAD

**Issue by FFdhorkin** [pnpm/action-setup#4]
The github action to install pnpm doesn't appear to work if you are on windows. Running on Linux and OSX appears to work as expected.

I've got an example file here, and the output below as an image (I'm trying to add pnpm support to Cypress.io): https://github.com/FFdhorkin/github-action/blob/feature/pnpm-support/.github/workflows/example-basic-pnpm.yml

![image](https://user-images.githubusercontent.com/59899746/91359930-5da87880-e7aa-11ea-8b28-1290876d8cf7.png)

**Comment by KSXGitHub** [comment]
This bug seems to have been caused by [pnpm self-installer](https://github.com/pnpm/self-installer) sometimes not working correctly on Windows.

@zkochan Can you take a look at this?

**Comment by KSXGitHub** [comment]
I have released [v2.0.0-rc.0](https://github.com/pnpm/action-setup/releases/tag/v2.0.0-rc.0). Try if it works on Windows.

**Comment by meeroslav** [comment]
I got same error with Ubuntu and version `2.0.1`:
```
Run pnpm/action-setup@v2.0.1
  with:
    version: 6.7.6
    dest: ~/setup-pnpm
    run_install: null
Running self-installer...
  [stdin]:4225
  
  SyntaxError: Unexpected end of input
      at new Script (vm.js:84:7)
      at createScript (vm.js:258:10)
      at Object.runInThisContext (vm.js:306:10)
      at Object.<anonymous> ([stdin]-wrapper:9:26)
      at Module._compile (internal/modules/cjs/loader.js:959:30)
      at evalScript (internal/process/execution.js:80:25)
      at internal/main/eval_stdin.js:29:5
      at Socket.<anonymous> (internal/process/execution.js:192:5)
      at Socket.emit (events.js:215:7)
      at endReadableNT (_stream_readable.js:1184:12)
Error: Something does wrong, self-installer exits with code 1
```

Strangely enough, this happened in the matrix with 36 combinations, where all the other combinations worked.

I cannot reproduce it again, unfortunately.

**Comment by KSXGitHub** [comment]
There's no response, I'm closing this.
