### ISSUE TITLE
The `add-path` command is deprecated

### ISSUE THREAD

**Issue by pattisahusiwa** [pnpm/action-setup#5]
Error message when running `pnpm/action-setup@v1.2.0`

> The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by brettz9** [comment]
any idea why https://github.com/marketplace/actions/setup-pnpm is still showing 1.2.0 as the latest?

**Comment by KSXGitHub** [comment]
@brettz9 I don't have the authority to publish action to the marketplace.

cc @zkochan
