### ISSUE TITLE
add-path is deprecated

### ISSUE THREAD

**Issue by aminya** [pnpm/action-setup#6]
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by KSXGitHub** [comment]
Weird. I have upgraded `@actions/core` to 1.2.6 since [v1.2.1](https://github.com/pnpm/action-setup/releases/tag/v1.2.1). What version are you using?

**Comment by aminya** [comment]
I am using the version which is in the readme: 
https://github.com/pnpm/action-setup#just-install-pnpm

I can't use `v1` since it does not exist!
