### ISSUE TITLE
Not working when install folder is subfolder

### ISSUE THREAD

**Issue by Joren97** [pnpm/action-setup#60]
I am trying setup pnpm in a subfolder of my repository, but this is not working.

**Comment by HashemKhalifa** [comment]
facing the same issue, with monorepo subfolders

**Comment by melMass** [comment]
Can you clarify a bit more? 
It works fine with monorepos

**Comment by gsimone** [comment]
@melMass the problem is when the pnpm-lock is not in the root dir.
Eg.

```bash
my-apps
	app
		pnpm-lock.yaml // <= we should be able to set this
    not-a-pnpm-app
	another-not-pnpm-app
```

**Comment by melMass** [comment]
What monorepo manager do you use? Seems like a strange setup, but why not just cd to it?

**Comment by Joren97** [comment]
Seems like I have found a solution. I added a version to use to the step. Also just `cd` into it did work. Closing this.
