### ISSUE TITLE
Add major tag `v2`

### ISSUE THREAD

**Issue by paescuj** [pnpm/action-setup#63]
What do you think about adding a tag `v2` which points to the latest v2 release?

This tag could then also be used in the examples in the README, so that it does not have to be updated with every release.

There is a major tag for [`v1`](https://github.com/pnpm/action-setup/tree/v1).

**Comment by KSXGitHub** [comment]
There's already a `v2` branch.

**Comment by KSXGitHub** [comment]
What do you think about editing to examples to use `pnpm/action-setup@v2`?

/cc @zkochan

**Comment by zkochan** [comment]
We don't frequently release new versions, so I don't really see the point.

**Comment by mrienstra** [comment]
I came here to ask about this very thing -- I was confused as to why this GitHub Action suggests specifying an exact (X.Y.Z) version (currently `pnpm/action-setup@v2.2.4`, with one exception*), when most GitHub Actions seem to suggest specifying only the major version, e.g. [`actions/checkout@v3`](https://github.com/actions/checkout#readme).

Would it be difficult to start tagging releases with [`v2`](https://github.com/pnpm/action-setup/tree/v2) in addition to e.g. [v2.2.4](https://github.com/pnpm/action-setup/tree/v2.2.4)? (Hopefully I'm correct in assuming that would resolve this issue)

---
*: While I was poking around, noticed one of the three was out of sync: https://github.com/pnpm/action-setup/pull/64

**Comment by pitgrap** [comment]
Just a stupid question: I'm using "pnpm/action-setup@v2" and that means I'm not using th latest one? :O

**Comment by KSXGitHub** [comment]
@pitgrap You are using the latest one.

**Comment by mrienstra** [comment]
@KSXGitHub, I think `v2` is currently even with `v2.2.3`, so slight behind `v2.2.4`:
- https://github.com/pnpm/action-setup/compare/v2...v2.2.4
- https://github.com/pnpm/action-setup/compare/v2...v2.2.3

_(but maybe I'm missing something)_

**Comment by KSXGitHub** [comment]
@mrienstra I see. It seems @zkochan forgot to update `v2` when he published `v2.2.4`. Anyway, `v2` is up-to-date now.

**Comment by mrienstra** [comment]
There are two parts to this issue:

1. `v2` should be kept current: it sounds like this is the intention and generally the case, so it seems like that part of this issue has been resolved for now.
2. Changing README to show `pnpm/action-setup@v2` (drop minor & patch version numbers): where did we land on this? Personally, I think it would reduce confusion. But if the official word is "not changing at this time", then I think this issue can be closed.

**Comment by KSXGitHub** [comment]
@mrienstra I don't object your second point.

**Comment by mrienstra** [comment]
Optimistically opened a PR. :)

**Comment by paescuj** [comment]
Thank you, guys!
