### ISSUE TITLE
 The `save-state` command is deprecated

### ISSUE THREAD

**Issue by zigang93** [pnpm/action-setup#72]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

![Screenshot 2023-01-03 at 8 41 47 AM](https://user-images.githubusercontent.com/11520821/210287582-38847e17-ab62-472f-8103-441249edff6e.png)

**Comment by KSXGitHub** [comment]
Is this still an issue?

**Comment by zigang93** [comment]
Closed due to issue been solved
