### ISSUE TITLE
Make `version` optional

### ISSUE THREAD

**Issue by nicodes** [pnpm/action-setup#85]
I think the mandatory `version` should be made optional and default to the latest stable. This will lower the entry barrier for first time users, and can cause confusion with the action version vs `pnpm` version.

Current:
```
- uses: pnpm/action-setup@v2
        with:
          version: 7
```

Proposed:
```
- uses: pnpm/action-setup@v2
```

**Comment by KSXGitHub** [comment]
I would prefer to give pnpm the freedom to make breaking changes without fear of breaking existing CIs.

@zkochan What do you think?

**Comment by KSXGitHub** [comment]
If `version` is not specified, `packageManager` field in `package.json` would be required. If both don't exist, there would be error.

The reason it was made an error was because we'd like to have to freedom of making breaking changes without fear of breaking existing CIs.
