### ISSUE TITLE
node20 support

### ISSUE THREAD

**Issue by MikeMcC399** [pnpm/action-setup#99]
Please provide a new release of  [pnpm/action-setup](https://github.com/pnpm/action-setup) which runs under `node20` as Node.js `16` reached [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) on Sep 11, 2023.

https://github.com/pnpm/action-setup/blob/0b715c7ebbf3cf2174d1386336c5f6d3d8d5504a/action.yml#L22-L25

See the announcement [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

Edit: Removed the request for a certain release number.

**Comment by zkochan** [comment]
Wouldn't that only affect the `pnpm/action-setup`? Why should it be a major version bump?

**Comment by zkochan** [comment]
I am not sure why do they mark this as breaking if only the action's own runtime changes. The projects using the action will not run on a different node.js version.

**Comment by MikeMcC399** [comment]
@zkochan 

If you are confident that nothing will break then you don't need a new major version of course.

**Comment by MikeMcC399** [comment]
@zkochan 

Thanks for your update and I'm sorry that this could be a time-consuming task for you. I guess it will be about 6 months until GitHub finally blocks `node16`.

**Comment by MikeMcC399** [comment]
GitHub is now producing the expected deprecation warning, for instance:

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: pnpm/action-setup@v2, actions/cache@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

The also impact `actions/cache@v3` listed in the [README](https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time).

**Comment by MikeMcC399** [comment]
The warning has been disabled temporarily, as it became clear that GitHub's own actions also were not ready.

**Comment by oanaOM** [comment]
The warning is back: 
![image](https://github.com/pnpm/action-setup/assets/15228388/f0b4e2f0-ce38-4e2c-916a-7d40f51c38df)

Is the work to update node version on the roadmap for the following months?

**Comment by MikeMcC399** [comment]
@oanaOM 

Your error message shows that you are using [pnpm/action-setup@v2.2.1](https://github.com/pnpm/action-setup/releases/tag/v2.2.1) from Feb 2022.

If you specify `pnpm/action-setup@v2` (or `pnpm/action-setup@v2.4.0`) you should not see this warning which refers to `node12` not `node16`

**Comment by oanaOM** [comment]
Ah, you are very right. Once I changed the version of the action I don't see the warning anymore. thanks you for your help!

**Comment by pavelzw** [comment]
![image](https://github.com/pnpm/action-setup/assets/29506042/38778c64-5574-4abf-88e0-4440431150a0)
the warning also gets produced with the latest version `2.4.0`

**Comment by MikeMcC399** [comment]
I'm not seeing any warnings on GitHub-hosted runners at this time, however the GitHub team said they wanted to re-enable the warnings again soon.

If this issue is not able to be resolved soon, then I would convert from using `pnpm/action-setup` and instead install pnpm with npm i.e. `npm install pnpm@8 -g` since the call that I'm looking at doesn't use any of the parameters of the action apart from the version number.

**Comment by erikburt** [comment]
Managed a little workaround of some stuff in #110. Could probably use some help testing it.

**Comment by jrr** [comment]
I'm seeing the deprecation warning from hosted runners today:

<img width="693" alt="image" src="https://github.com/pnpm/action-setup/assets/164652/084b9589-ee3a-443d-a3f6-1b6baaee6392">

And for google:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: pnpm/action-setup@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.Show less
 ```

**Comment by the-dijkstra** [comment]
![image](https://github.com/pnpm/action-setup/assets/9967336/cfde3138-7cfd-4c93-8b9b-e5d613a518de)

**Comment by PatrikBird** [comment]
### Possible workaround for you?
I figured out that I didn't need `pnpm action/setup`. I just enabled `corepack` in the CI, which will respect the packageManager field in package.json.

It **seems** there are little/no drawbacks of using this approach. See [comment](https://github.com/pnpm/action-setup/issues/105#issuecomment-1806359190) by zkochan.

This just works:
```yaml
- run: corepack enable
- uses: actions/setup-node@v4
  with:
    node-version: 20
    cache: "pnpm"

- name: Install dependencies
  run: pnpm install
```
Full workflow for reference: https://raw.githubusercontent.com/PatrikBird/website/main/.github/workflows/analyze_bundle.yaml

Maybe that's helpful to anyone. Have a nice day 🌞

**Comment by zkochan** [comment]
:ship: v3.0.0

**Comment by MikeMcC399** [comment]
Thank you for resolving this issue! 👍🏻 

I see 
- [release v3.0.0](https://github.com/pnpm/action-setup/releases/tag/v3.0.0) and
- [branch v3](https://github.com/pnpm/action-setup/tree/v3)

updated through 
- PR https://github.com/pnpm/action-setup/pull/110
